// @ts-check

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const projectDir = path.resolve(__dirname, "..");
const buildDir = path.join(projectDir, ".build");
const distDir = path.join(projectDir, "dist");
const entryPath = path.join(buildDir, "mdopen-binary-entry.js");
const options = parseArgs(process.argv.slice(2));
const outputPath = path.resolve(
  projectDir,
  options.outfile || path.join("dist", process.platform === "win32" ? "mdopen.exe" : "mdopen"),
);

fs.mkdirSync(buildDir, { recursive: true });
fs.mkdirSync(distDir, { recursive: true });

const textAssets = {
  "mdopen.css": readText("assets/mdopen.css"),
  "mdopen-overrides.css": readText("assets/mdopen-overrides.css"),
  "demo.css": readText("assets/styles/demo.css"),
  "readthedocs.css": readText("assets/styles/readthedocs.css"),
};

const fontAssets = Object.fromEntries(
  fs.readdirSync(path.join(projectDir, "assets", "styles", "fonts"))
    .filter((name) => fs.statSync(path.join(projectDir, "assets", "styles", "fonts", name)).isFile())
    .map((name) => [
      name,
      fs.readFileSync(path.join(projectDir, "assets", "styles", "fonts", name)).toString("base64"),
    ]),
);

const template = readText("templates/mdopen.html");
const mermaidScript = readText("templates/mermaid-script.html");
const rendererSource = readText("renderer.js");

fs.writeFileSync(entryPath, renderEntry({
  buildProjectDir: projectDir,
  textAssets,
  fontAssets,
  template,
  mermaidScript,
  rendererSource,
}));

const buildArgs = [
  "build",
  "--compile",
  ...(options.target ? ["--target", options.target] : []),
  "--outfile",
  outputPath,
  entryPath,
];

const build = spawnSync("bun", buildArgs, {
  cwd: projectDir,
  stdio: "inherit",
});

if (build.error) {
  console.error(`mdopen: binary build failed: ${build.error.message}`);
  process.exit(1);
}

if (build.status !== 0) {
  process.exit(build.status || 1);
}

console.log(outputPath);

function readText(relativePath) {
  return fs.readFileSync(path.join(projectDir, relativePath), "utf8");
}

function parseArgs(args) {
  const parsed = { target: process.env.MDOPEN_BINARY_TARGET || "", outfile: process.env.MDOPEN_BINARY_OUTFILE || "" };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--target") {
      parsed.target = requireValue(args[++index], "--target");
    } else if (arg.startsWith("--target=")) {
      parsed.target = arg.slice("--target=".length);
    } else if (arg === "--outfile") {
      parsed.outfile = requireValue(args[++index], "--outfile");
    } else if (arg.startsWith("--outfile=")) {
      parsed.outfile = arg.slice("--outfile=".length);
    } else {
      console.error(`Usage: bun scripts/build-binary.js [--target BUN_TARGET] [--outfile PATH]`);
      console.error(`Unknown option: ${arg}`);
      process.exit(2);
    }
  }

  return parsed;
}

function requireValue(value, option) {
  if (!value) {
    console.error(`mdopen: ${option} requires a value`);
    process.exit(2);
  }
  return value;
}

function renderEntry(data) {
  return `#!/usr/bin/env bun
// Generated by scripts/build-binary.js. Do not edit.
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const RENDERER_REQUIRE_CACHE = {
  "highlight.js": require("highlight.js"),
  "markdown-it": require("markdown-it"),
  "markdown-it-deflist": require("markdown-it-deflist"),
  "markdown-it-footnote": require("markdown-it-footnote"),
  "markdown-it-mark": require("markdown-it-mark"),
  "markdown-it-sub": require("markdown-it-sub"),
  "markdown-it-sup": require("markdown-it-sup"),
  "markdown-it-task-lists": require("markdown-it-task-lists"),
};

const BUILD_PROJECT_DIR = ${JSON.stringify(data.buildProjectDir)};
const TEMPLATE = ${JSON.stringify(data.template)};
const MERMAID_SCRIPT = ${JSON.stringify(data.mermaidScript)};
const RENDERER_SOURCE = ${JSON.stringify(data.rendererSource)};
const TEXT_ASSETS = ${JSON.stringify(data.textAssets, null, 2)};
const FONT_ASSETS = ${JSON.stringify(data.fontAssets, null, 2)};

function usage() {
  console.error("Usage: mdopen FILE.md");
}

function fail(message, code = 1) {
  console.error(\`mdopen: \${message}\`);
  process.exit(code);
}

function isMingwSession() {
  return Boolean(process.env.MSYSTEM || process.env.MINGW_PREFIX);
}

function cygpathToWindows(value) {
  if (process.platform !== "win32" || !isMingwSession() || !value.startsWith("/")) {
    return value;
  }

  const cygpath = spawnSync("cygpath", ["-w", value], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  });

  if (cygpath.status === 0 && cygpath.stdout.trim()) {
    return cygpath.stdout.trim();
  }

  const drivePath = value.match(/^\\/([a-zA-Z])(?:\\/(.*))?$/);
  if (drivePath) {
    const rest = drivePath[2] ? \`\\\\\${drivePath[2].replaceAll("/", "\\\\")}\` : "\\\\";
    return \`\${drivePath[1].toUpperCase()}:\${rest}\`;
  }

  return value;
}

function commandExists(command) {
  const probe = process.platform === "win32" ? "where" : "command";
  const args = process.platform === "win32" ? [command] : ["-v", command];
  const result = spawnSync(probe, args, { stdio: "ignore", shell: process.platform !== "win32" });
  return result.status === 0;
}

function pathStartsWith(child, parent) {
  const relative = path.relative(
    process.platform === "win32" ? parent.toLowerCase() : parent,
    process.platform === "win32" ? child.toLowerCase() : child,
  );
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function openHtml(outputPath) {
  if (process.env.MDOPEN_NO_OPEN === "1") {
    return;
  }

  let result;
  if (process.platform === "darwin") {
    result = spawnSync("open", [outputPath], { stdio: "ignore" });
  } else if (process.platform === "linux") {
    if (!commandExists("xdg-open")) {
      fail(\`xdg-open is not on PATH; generated HTML was not opened: \${outputPath}\`);
    }
    result = spawnSync("xdg-open", [outputPath], { stdio: "ignore" });
  } else if (process.platform === "win32") {
    result = spawnSync("cmd.exe", ["/c", "start", "", cygpathToWindows(outputPath)], {
      stdio: "ignore",
      windowsHide: true,
    });
  } else {
    fail(\`unsupported platform: \${process.platform}\`);
  }

  if (result.error) {
    fail(\`could not open generated HTML: \${result.error.message}: \${outputPath}\`);
  }
  if (typeof result.status === "number" && result.status !== 0) {
    fail(\`could not open generated HTML: opener exited with status \${result.status}: \${outputPath}\`);
  }
}

function writeEmbeddedRuntime(outdir) {
  fs.mkdirSync(outdir, { recursive: true });
  for (const [name, content] of Object.entries(TEXT_ASSETS)) {
    fs.writeFileSync(path.join(outdir, name), content);
  }

  const templatesDir = path.join(outdir, "templates");
  fs.mkdirSync(templatesDir, { recursive: true });
  fs.writeFileSync(path.join(templatesDir, "mdopen.html"), TEMPLATE);
  fs.writeFileSync(path.join(templatesDir, "mermaid-script.html"), MERMAID_SCRIPT);

  const fontsDir = path.join(outdir, "fonts");
  fs.mkdirSync(fontsDir, { recursive: true });
  for (const [name, content] of Object.entries(FONT_ASSETS)) {
    fs.writeFileSync(path.join(fontsDir, name), Buffer.from(content, "base64"));
  }
}

function rendererRequire(specifier) {
  return RENDERER_REQUIRE_CACHE[specifier] || require(specifier);
}

function runEmbeddedRenderer(input, templatePath, output, pageTitle, cssHref, defaultStyle) {
  const previousArgv = process.argv;
  const module = { exports: {} };
  const renderer = new Function(
    "require",
    "module",
    "exports",
    "process",
    "__filename",
    "__dirname",
    RENDERER_SOURCE,
  );

  process.argv = [
    process.execPath,
    "renderer.js",
    input,
    templatePath,
    output,
    pageTitle,
    cssHref,
    defaultStyle,
  ];

  try {
    renderer(rendererRequire, module, module.exports, process, "renderer.js", ".");
  } finally {
    process.argv = previousArgv;
  }
}

const args = process.argv.slice(2);
if (args.length !== 1) {
  usage();
  process.exit(2);
}

const inputArg = cygpathToWindows(args[0]);
const input = path.resolve(inputArg);

let inputStat;
try {
  inputStat = fs.statSync(input);
} catch {
  fail(\`file not found: \${args[0]}\`);
}

if (!inputStat.isFile()) {
  fail(\`file not found: \${args[0]}\`);
}

const outdir = path.join(os.tmpdir(), "mdopen");
const title = path.basename(input, path.extname(input));
const output = path.join(outdir, \`\${title}.html\`);
const reviewDir = path.join(BUILD_PROJECT_DIR, "review");
const defaultStyle = pathStartsWith(input, reviewDir) ? "demo" : "default";
const templatePath = path.join(outdir, "templates", "mdopen.html");

writeEmbeddedRuntime(outdir);
runEmbeddedRenderer(input, templatePath, output, title, "mdopen.css", defaultStyle);
openHtml(output);
console.log(output);
`;
}
